spring.config.import=optional:file:.env[.properties]
spring.application.name=exagen
server.port=8081

# Database
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

auth.public-key-url=http://localhost:8080/api/v1/auth/public-key-pem

# Docs
springdoc.swagger-ui.path=/docs